name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: npm install
      - name: Build and Test
        run: npm run build && npm test
      - name: Lint
        run: npm run lint
      - name: Package
        run: npm run package
